// GENERATED by tool/gen_build_info.sh — do not hand-edit.
library;

/// Build/version metadata, injected at build time.
class BuildInfo {
  static const String version = '0.4.0';
  static const int build = 52;
  static const String commit = '5a4fe98';
  static const String commitSubject = 'What\'s there The Movies tab — a search field, a Continue Watching shelf (horizontal cards with resume progress bars), then a reflowing poster grid that goes from 3 columns on a phone to as many as fit a desktop window (SliverGridDelegateWithMaxCrossAxisExtent, so it\'s truly responsive, not breakpoint-hacked). Posters cache through the content cache with a graceful film-glyph placeholder; snapshot-first so the catalog paints instantly on a cold start. The detail page — responsive: poster beside the metadata on wide screens, stacked on phones. Shows title/year/runtime/resolution, a track summary (\'Audio: 日本語, English Dub · Subtitles: English\'), overview, and a Play / Resume from Xm button with a Start over option and a resume progress bar. Series episodes show their SxxExx context. The player — this is where the multi-track design pays off: Landscape-locked, immersive fullscreen, built on the central PlaybackController (so PiP attaches later with no rework). Audio-track picker (the 🎚 icon) — switching to \'English dub\' re-opens the stream through the server\'s zero-CPU remux at the current position. Only appears when there\'s more than one track. Subtitle picker (the 💬 icon) — text tracks (embedded + sidecar) fetched as WebVTT and rendered as a clean overlay via setClosedCaptionFile; \'Off\' clears it. Image subs are correctly hidden (they\'d need OCR). Server-side resume — opens at the saved position, reports progress every 20 seconds and on exit, so Continue Watching stays truthful across devices. Default audio uses the direct signed URL (perfect client-side seeking); non-default uses server-seek, exactly as the design intended. Registration — movies service is manifest-gated (movies:read), grouped under Media in the desktop sidebar, and deliberately registered after the core dock services so it never bumps the Media/Files/Music/Torrent dock — same call as Photos.';
  static const String date = '2026-07-19';

  static String get label =>
      build == 0 ? '$version (dev)' : '$version (build $build)';
}
