// GENERATED by tool/gen_build_info.sh — do not hand-edit.
library;

/// Build/version metadata, injected at build time.
class BuildInfo {
  static const String version = '0.4.0';
  static const int build = 123;
  static const String commit = 'e312d07';
  static const String commitSubject = 'Tools: renew the macOS profile for `flutter run`, not just builds';
  static const String date = '2026-09-04';

  static String get label =>
      build == 0 ? '$version (dev)' : '$version (build $build)';
}
