#!/usr/bin/env bash
# Regenerate lib/core/version/build_info.dart from git + pubspec. Run before a
# release build (or wire into CI). Safe to run anytime; commit the result so
# the version shown in the app matches the commit it was built from.
#
#   bash tool/gen_build_info.sh
set -euo pipefail
cd "$(dirname "$0")/.."

version=$(grep '^version:' pubspec.yaml | sed 's/version:[[:space:]]*//; s/+.*//')
build=$(git rev-list --count HEAD)
commit=$(git rev-parse --short HEAD)
subject=$(git log -1 --pretty=%s | sed "s/'/\\\\'/g")
date=$(git log -1 --date=short --pretty=%cd)

out=lib/core/version/build_info.dart
cat > "$out" <<EOF
// GENERATED by tool/gen_build_info.sh — do not hand-edit.
library;

/// Build/version metadata, injected at build time.
class BuildInfo {
  static const String version = '$version';
  static const int build = $build;
  static const String commit = '$commit';
  static const String commitSubject = '$subject';
  static const String date = '$date';

  static String get label =>
      build == 0 ? '\$version (dev)' : '\$version (build \$build)';
}
EOF

echo "wrote $out: $version+$build ($commit)"
